"""update driver profile

Revision ID: 1f4ab1fe3499
Revises: 3a45236cd916
Create Date: 2025-09-26 06:01:42.903461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f4ab1fe3499'
down_revision: Union[str, None] = '3a45236cd916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_driver', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('dim_driver', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_driver', 'phone')
    op.drop_column('dim_driver', 'email')
    # ### end Alembic commands ###
