"""added location name and updated trip info

Revision ID: 7908b5347ebe
Revises: 1f4ab1fe3499
Create Date: 2025-09-26 07:56:56.176112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7908b5347ebe'
down_revision: Union[str, None] = '1f4ab1fe3499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_location', sa.Column('location_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('fact_trip', sa.Column('origin_location_id', sa.Integer(), nullable=True))
    op.add_column('fact_trip', sa.Column('destination_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fact_trip', 'dim_location', ['origin_location_id'], ['location_id'])
    op.create_foreign_key(None, 'fact_trip', 'dim_location', ['destination_location_id'], ['location_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_trip', type_='foreignkey')
    op.drop_constraint(None, 'fact_trip', type_='foreignkey')
    op.drop_column('fact_trip', 'destination_location_id')
    op.drop_column('fact_trip', 'origin_location_id')
    op.drop_column('dim_location', 'location_name')
    # ### end Alembic commands ###
